### PR TITLE
Fixed random UID generation in reader_analyzer.c

### PR DESCRIPTION
**Pull request by NathanielJS1541**
# What's new

- The random UID generation has been changed to derive the 4-byte CUID from the randomly generated 7-byte UID, whereas it previously was a sepearate randomly generated number. This caused problems as the CUID saved to the Mfkey32.log file was different to what was used to establish the crypto algorithm, and could lead to keys being incorrectly cracked using mfkey32v2.

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
Some more info would be nice.

E.g. related issues (like #244 or #241), replication steps of issue / fix.

Other than that, will have a look

**Comment by ClaraCrazy** [comment]
@NathanielJS1541 You wanna have a laugh? "dev" branch was renamed as a joke yesterday to why-no-worky. The fake dev branch was to mess with someone. I'm so sorry :rofl: Can you fix the conflicts or should we? haha

**Comment by ClaraCrazy** [comment]
Actually, forget it. That would be too much effort. We'll fix it ourselves after testing it

**Comment by NathanielJS1541** [comment]
Trust my luck to start working in the joke branch 😂... I was gonna say it's hard to test in the dev branch because the Detect Reader function seems to be broken to begin with (hence why my initial commit had my changes commented it out). I ended up adding them on top of the main branch to test and they worked there. Sorry I also forgot to add detail as I was discussing it in the discord a couple of days ago, I can add some detail accross from there. I can type fast but my brain works slow... sorry.

**Comment by ClaraCrazy** [comment]
Take your time :smile:

**Comment by ClaraCrazy** [comment]
we fixed it :smile:

**Comment by NathanielJS1541** [comment]
Basically the changes in #6b91c66 added two functions to generate random UIDs:
```C
reader_analyzer_nfc_data[ReaderAnalyzerNfcDataMfClassic].cuid = rand(); //XXX
furi_hal_random_fill_buf((uint8_t*)&reader_analyzer_nfc_data[ReaderAnalyzerNfcDataMfClassic].uid, 7);
```

But those changes actually generate two UIDs. One of them is used by the card emulation for the Detect Reader function, and the other 4-byte one generated with `rand()` is the one that ends up being saved to Mfkey32.log. The CUID (4 bytes) should really just be the last 4-bytes of the larger 7-byte UID.

The problems I referenced would lead to an incorrect key being reported when using mfkey32v2:
This line is what the flipper saved:
`Sec 0 key A cuid 2f869a28 nt0 59bd4e1a nr0 9c599ed7 ar0 ecfced6a nt1 aa4240f2 nr1 0c0fcff5 ar1 3f59ca15` which indicates a UID of `2f869a28`, but the reader found the UID of `eafc09cf5767b6`:
pm3_tracelog

This would lead to the key "FFFFFFFFFFFF" being cracked to this:
keys.txt
since the UID stored by the flipper was wrong. This commit ensures that the two UIDs result in the correct keys being generated by the reader as it detectes the correct UID.

**Comment by Willy-JL** [comment]
yup, all rebased now. we'll do some testing in a bit, and thanks for the detailed info!

**Comment by NathanielJS1541** [comment]
I hope that explains it ok

**Comment by ClaraCrazy** [comment]
Sounds alright, one slight issue I have tho, is that #241 claims the detect reader function is broken too. So I feel like we're basing stuff off of a currently broken feature? 

Not an NFC expert, so I cant really judge that. Any ideas?

**Pull request merged**
