### PR TITLE
Added Universal Remotes + Custom Icons

### PR DESCRIPTION
**Pull request by uwuw7**
# What's new

- Added New Digital Sign, Monitor, and LED Universal Remotes in the Infrared Universal Remote GUI
- Added custom icons for respective remotes (Play, Stop, Input, Exit, and Flash)
- Added Samsung.ir as default resource, and SamsungGeneric.txt as default IR Remote Resource

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
1. What makes you think that *FOR THE REVIEWER* should be ticked by the requester?
2. Dont PR to main... main is for releases. You PR into dev

**Comment by ClaraCrazy** [comment]
Lint failed. Please run the fbt linter over your code :smile:

**Comment by uwuw7** [comment]
Yes maam, will do as soon as I can

**Comment by Willy-JL** [comment]
looks like you also have some merge conflicts due to today's merge. i'll fix all that up for you

**Comment by Willy-JL** [comment]
LGTM, thanks!

**Pull request merged**
