### PR TITLE
V47 Release Candidate Changes

### PR DESCRIPTION
**Pull request by Willy-JL**
### Added:
- New Namespoof implementation, change device name now affects BT name, BT MAC, serial number and serial port
- Xtreme Settings: New Lock on Boot option to have Flipper lock immediately after switching on
- Xtreme Settings: New Charge Cap option to limit max charging percent
- Xtreme Settings: New Angry Level option to change  Flipper's mood
- Archive: Complete overhaul of file menu with added file management, now split in 2 parts:
  - Action menu (press / hold Ok): Normal file actions like pin, run in app...
  - Manage menu (hold Back): New menu with cut, copy, paste, new dir, rename and delete functionality
- Loader: Allow preloading extmainapps, now GPIO and iButton are external
- UL: Desktop: Add setting to show clock oin statusbar (by [gid9798](https://github.com/gid9798))
- OFW: RFID: Add support for Nexkey/Nexwatch (by [mauimauer](https://github.com/mauimauer))
- OFW: BadKB: Option to pause script (by [nminaylov](https://github.com/nminaylov))

### Updated:
- Xtreme Assets: All icons are now supported for replacing
- Xtreme Assets: Icons are now swapped system-wide (external apps excluded)
- Xtreme Assets: Unload icons when opening external apps and reload when out, saves RAM for heavy apps
- Startup: Improved boot process and load storage service first
- Storage: Rename now is an actual rename instead of copy+delete, renaming is now instantaneous
- BadKB: Options restricted by `BT_ID` and `ID` commands now show that they're locked
- Storage: Better move from internal to external, cleaned up internal storage
- Storage: Improved fs error handling in various apps
- BT Remote: Merged YT Shorts and TikTok menus, fixed issues on iOS
- SubGhz: Removed region lock
- Ported extended keyboard to WiFi Marauder (by @xMasterX)
- Updated Apps:
  - TOTP (Authenticator) [(by akopachov)](https://github.com/akopachov/flipper-zero_authenticator) (+ Add option to set custom fonts)
  - NMEA GPS UART [(by ezod)](https://github.com/ezod/flipperzero-gps) (GLL support)
  - WiFi Marauder [(by 0xchocolate)](https://github.com/0xchocolate/flipperzero-firmware-with-wifi-marauder-companion)
- UL: SubGhz Remote: Refactor and improvements (by [gid9798](https://github.com/gid9798))
- UL: WiFi Marauder: Updated with sniff pmkid (by [clipboard1](https://github.com/clipboard1))
- UL: NFC: Mifare mini with SAK 0x89 support
- UL: SubGhz: More CAME Atomo support, move extended range settings check, many improvements and refactor fixes (by @xMasterX and [gid9798](https://github.com/gid9798))
- OFW: BadKB: Add fr-FR-mac key layout (by [FelixLgr](https://github.com/FelixLgr))
- OFW: Progress on C2 crash problems

### Fixed:
- Mobile App: Fixed issues with crashing and not emulating files
- BadKB: Remember option now saves keys properly
- PIN Code: Reset key combo also clears internal storage (to erase private U2F key)
- Desktop Settings: File moved to internal storage (to keep PIN private)
- Bluetooth: Forget paired devices also forgets for BT remote and BadKB
- BT Remote: No longer use a default MAC, use one based on device UDN / Namespoof
- Desktop: Fixed SFW pack animation distribution with mood status
- U2F: Moved counter to SD card, only private key file is on internal storage
- Notification: Setting file reworked and moved to external storage
- Keyboard: Fixed memory management issues
- Infrared: Fixed disabling OTG power (thanks @xMasterX!)
- BadKB: Migrate old badusb folder if new one doesn't exist (properly this time)
- RGB Backlight: Refactored to not need a service process
- Archive: Fixed scene handling, folder history preserved after opening dialogs
- About: Hold right on desktop can now go napping, added more info to firmware page
- UL: Fixed CLI app crashes (thanks @xMasterX!)

### Removed:
- Desktop: Removed obsolete ligma animation

### CODE REVIEW

**Comment by Willy-JL** [comment]
Had forgotten to bump version, so second merge :/

**Review by ClaraCrazy — APPROVED** [review]
moron

**Review by ClaraCrazy — APPROVED** [review]
reeeee

**Comment by ramonbypasser010110** [comment]
Hey how do u update xtreme again if u flashed my flipper wit the old xtreme like 3 weeks ago

**Pull request merged**
