### PR TITLE
V40 Release Candidate Changes

### PR DESCRIPTION
**Pull request by ClaraCrazy**
# What's new

## Added:
- Xtreme App
  - Graphics changer
  - Animation changer
  - Animation Speed changer
  - Battery style switch
  - Level changer
  - Subghz unlocker
 
- Show device info with long-press `Arrow Right`
- New [docs](https://github.com/ClaraCrazy/Flipper-Xtreme/wiki/1.-File-Formats)

## Updated:
- All Apps & games
- Compiler
  - New Asset handler
  - Clean build mode

- Battery Icon

## Fixed:
- Various bugs mentioned by the community

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
someone figure out why this fails with 0% coverage.. thx

**Comment by schmenn** [comment]
looks good 👍

**Review by Willy-JL — APPROVED** [review]
LGTM! :100:

**Review by jbohack — APPROVED** [review]
lgtm

**Comment by ClaraCrazy** [comment]
JESUS FUCKING CHRIST SONARCLOUD HURRY TF UP AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request merged**
