### PR TITLE
V38 Release candidate changes

### PR DESCRIPTION
**Pull request by ClaraCrazy**
# What's new

## Added:
- Added Pong, Asteroids, CLI Bridge & Text Viewer
- Added Lowes & Wallgreens subghz playlist
- Added new Battery display-type
- Added Ford sub-GHz playlist
- Added SFW Manifest
- Added SFW level-up animations
- Added SFW mode to applications (Infrared, U2F, DAP, Unitemp, POCSAG & Weather Station)

## Updated:
- Updated Wii EC
- Updated Infrared
- Updated compiler
- Updated Passport assets
- Updated Fallback Animation
- Updated cycle length of animations
- Updated level-up animation framerate
- Updated missing descriptors of some GPIO modules

## Fixed:
- Fixed some Typos
- Fixed Pong notification
- Fixed Subghz Remote not closing to the app menu

## Removed:
- Removed duplicate game "2048"
- Removed broken App "USB Midi"

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Review by jbohack — APPROVED** [review]
release candidate lgtm

**Comment by ClaraCrazy** [comment]
maybe I wake up to this being approved, who knows

**Review by Agentirish — APPROVED** [review]
Go Go Gadget!

**Review by Agentirish — APPROVED** [review]

**Comment by ClaraCrazy** [comment]
oi bozo, you cant approve shit bc you arent even a dev for us

**Comment by schmenn** [comment]
nice nice

**Comment by ToXiCRaTt** [comment]
No tgz file😭😭😭🌹

**Pull request merged**
