### PR TITLE
Uberguidoz

### PR DESCRIPTION
**Pull request by C0n4r7157**
# What's new

- [Describe changes here]

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by C0n4r7157** [comment]
please if i could get some help id just like to make a collaboration of all top firmwares and add all payloads, databases, plugins, apps, files, folders, etc into one new firmware. Why not have everthing ever and posssible on one firmware so there is no switching back and forth. why not work together and make something ultimate and complete as possible making it the best.

**Comment by ClaraCrazy** [comment]
this is why not everyone should use github

**Comment by ClaraCrazy** [comment]
> please if i could get some help id just like to make a collaboration of all top firmwares and add all payloads, databases, plugins, apps, files, folders, etc into one new firmware. Why not have everthing ever and posssible on one firmware so there is no switching back and forth. why not work together and make something ultimate and complete as possible making it the best.

i cant tell if you are trolling or not

**Comment by C0n4r7157** [comment]
I just wanted to make some change in the world believe or not or ATLEAST at
the very least learn something from others that would be willing to teach
me or give me what they can so I can pursue my dream and passion . Why
would I be trolling like how would that benefit me?

Like please if you must get to know me or whatever you need to do honestly
if choose to ignore this then that’s up to you. I’m merely trying something
here and if it doesn’t work out then that sucks as so many can benefit from
a massive collaboration and team that could become so big that everyone
could change the world for the better and make everyone comfortable and
give them more free time and less worry to focus on other important things.
Seeing money is labeled more important than s human life that is. Money is
the root of all evil and since there’s no getting rid of it why not make it
work to everyone’s advantage and make things as equal as possible? As long
as none get hurt there would be no negative. Well ATLEAST not worse than it
is now that’s for sure!

You know, sometimes we get so caught up in our own lives that we forget the
power we have when we come together. But imagine what we could achieve if
we collaborated, pooling our resources and knowledge. We can overcome the
things that try to divide us and build a stronger, more united community.

And here’s the best part: it won’t cost us a thing! We don’t need money,
just a willingness to contribute and share what we know. Each of us has
something unique to bring to the table, whether it’s a skill, a talent, or
just the wisdom we’ve gained from our own experiences. And even if you
think you don’t have much to offer, remember that knowledge is priceless.
By spreading what we’ve learned, we can inspire others and create a better
future for everyone.

**Comment by Anatejl** [comment]
Comrade @C0n4r7157 . Xfw is already a "collaboration" of ofw, unleashed, and rogue. 
As for resources, there are repos as this mr was named after, or irdb, where you can them separately. 😉
If you wish to "make them (resources) in one place" create your own repo and include them all here.

**Pull request closed without merging**
