### PR TITLE
Fix android app not finding flipper zero device

### PR DESCRIPTION
**Pull request by jl1990**
# What's new

- It should fix https://github.com/ClaraCrazy/Flipper-Xtreme/issues/205
- Little function refactoring
-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
Root cause identified to be something else, still thx for trying

**Comment by jl1990** [comment]
As you know this is exactly what was modified from your side that broke the functionality.
This is the cause of the app not finding the device, it was just this name change.
Same as in the official app they look for flipper string.

With this change the devices are found, the Mac bug should be fixed also in the android part, but that does not mean that this wasn't the root cause.

As discussed in the chat, good luck, last commit I do for the repo.

I cannot understand why you preferred to close the PR and keep the functionality broken

**Comment by Willy-JL** [comment]
@jl1990 
listen, what happened is:
- device_id should be `0x26`
- for some reason new chips and new flippers have `0x27`
- the app expects `0x26`
- (this is speculation) flipper devs had this issue, couldn't fix it properly, so they added "Flipper " in front
- we removed "Flipper " because it's stupid to shout to everyone "I HAVE A FLIPPER!"

your fix adds back the stupid fix OFW made. the actual fix is either figuring out why it turned to 0x27, or hardcode it to 0x26. we are in talks with unleashed, and with ofw, to look deeper into this issue. but adding back a temporary and stupid fix is not the right solution.

go cry somewhere else for your contribution stats buddy

**Comment by jl1990** [comment]
You know that even if you edit there is an history right? 
The code you changed broke the bt functionality.
You like it or not, after this "stupid fix" (that reverts back your mistake to the same code as official firmware had and was expected) it works.

Now as discussed previously, good luck with the repository, feel free to edit, history and facts won´t change 🥇

**Comment by Willy-JL** [comment]
thats the point of the edit? we would not edit if you weren't able to get back the original message? this is just for the lols?

but yes, exactly, you explained yourself what the problem with your fix is. it is bringing back what official firmware did. official firmware did the stupid fix. we will not keep the stupid fix.

**Comment by ClaraCrazy** [comment]
I am more than aware the history is there. in fact, im glad it is.

having said that. lets furi-fy that last message of yours too

**Pull request closed without merging**
