### PR TITLE
V41 Release Candidate Changes

### PR DESCRIPTION
**Pull request by ClaraCrazy**
# What's new

## Added:

- Bad Bluetooth (thanks @yocvito):
  - Renamed Bad USB to Bad KB
  - Config has switch between USB and BT, can change BT name and mac address
  - WARNING: you will need to move your files from SD/badusb to SD/badkb
- Internal storage browser
- External cc1101 gpio module support
- Multiple subghz protocols (thanks @xMasterX)
- Multiple Apps:
   - Brainfuck
   - Geiger Counter
   - Nightstand clock
   - Pomodoro
   - Rubiks Scrambler
- Xtreme settings features:
  - Detailed statusbar customization
  - Base graphics merged into asset packs, now NSFW is an asset pack
  - Asset packs support for animated icons, only levelup anim for now

## Updated:

- File browsers:
  - Fixed cursor jump bug
  - Fixed alphabetic sorting
  - Fixed issues with big folders (thanks @xMasterX)
  - Added option to sort folders before files in xfw app
- Default clock (left on desktop) is now nightstand, screen stays on, can change brightness
- Misc fixes and updates to xtreme settings app
- New "Firmware Updated" popup image
- Fixed up some bad assets
- SPI things
- Upstream updates

## Removed:

- Some more bad code

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
Sonar officially gave up

**Review by jbohack — APPROVED** [review]
lgtm :)

**Review by Willy-JL — APPROVED** [review]
yes

**Comment by ClaraCrazy** [comment]
godspeed

**Pull request merged**
