### PR TITLE
Improved NRF24 apps

### PR DESCRIPTION
**Pull request by Sil333033**
# What's new

- The NRF24 sniffer & mousejacker ran without module plugged in. Now before starting the sniff or mousejack there is a check to see if the NRF24 is connected. 

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
oi @Sil333033 you left your test in there, lol

**Comment by Sil333033** [comment]
The test in the TX test?

**Comment by ClaraCrazy** [comment]
yes...

**Comment by Sil333033** [comment]
My fault. is there anyhing else?

**Comment by ClaraCrazy** [comment]
image

**Comment by Sil333033** [comment]
ah, I thought it was a handy app for people making NRF24 pcb's to make sure everything works right.

**Comment by ClaraCrazy** [comment]
if you want that, you add a proper test mode into the app, and dont copy the entire libs folder to another place

**Comment by Sil333033** [comment]
The app is relatively simple and works fine when I watch along with a HackRF.
image

but its okay for now then ig

**Pull request closed without merging**
