### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by ClaraCrazy**
# What's new

- New readme icon

-----

- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
Day 1: It was a rough day on the Github sea. I requested access to the various Ports of the world, but so far not a single reviewer has approved my request.

**Review by NobodyWouldEverUseThis7 — APPROVED** [review]
Fuck branch protections

**Comment by gregoryca** [comment]
Maybe i'm out of line, but i like to deploy all my software by using pipelines.Ya'll need a pipeline which spits out an artifact as soon as a merge has been approved ?

Most actions can be done by using Ansible + Github Actions. That way there can be multiple deployment to for example the main branch, when a PR has been approved from for example a feature request branch.

Offcoarse you'll need a code sniffer/linter.
That way if the code sniffer/linter approves and merges the code another pipeline can create a new artifact/release.

If there is any interest holla at me !

**Comment by ClaraCrazy** [comment]
@gregoryca I have zero clue about how github works, lol... I'm just trying what ever works. I'd also love to add the github actions for automatic FW building to prs.. but idk how

Teach me your ways xD | msg me on Discord

**Pull request merged**
